In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Reading the Dataset
dataset = pd.read_csv(r"D:\AI course Tamil\CapstoneProject\2.Data Preprocessing\Preprocessed_project_risk.csv")
dataset

,Team_Size,Project_Budget_USD,Estimated_Timeline_Months,Complexity_Score,Stakeholder_Count,Past_Similar_Projects,External_Dependencies_Count,Change_Request_Frequency,Team_Turnover_Rate,Vendor_Reliability_Score,...,onehot__Contract_Type_Time & Materials,onehot__Client_Experience_Level_First-time,onehot__Client_Experience_Level_Occasional,onehot__Client_Experience_Level_Regular,onehot__Client_Experience_Level_Strategic,onehot__Team_Colocation_Fully Colocated,onehot__Team_Colocation_Fully Remote,onehot__Team_Colocation_Hybrid,onehot__Team_Colocation_Partially Colocated,Risk_Level
0,32.0,1526276.550,32,9.70,16,3,3,1.05,0.16,0.84,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,High
1,2.0,390790.150,9,2.72,9,0,2,2.61,0.42,0.79,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,Low
2,2.0,246674.760,6,2.04,7,1,0,0.83,0.55,0.89,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,Medium
3,12.0,1427830.630,17,7.54,16,0,5,2.42,0.33,0.84,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,High
4,24.0,1696746.640,24,6.68,17,0,2,0.16,0.36,0.86,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,9.0,731548.970,14,5.40,9,4,3,1.09,0.25,0.94,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,High
3996,9.0,492981.400,9,2.69,8,5,3,2.11,0.06,0.71,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,Medium
3997,12.0,1097040.650,24,8.82,10,2,4,0.52,0.23,0.95,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,High
3998,26.0,2650876.115,28,10.00,23,1,6,1.19,0.30,0.50,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,High
3999,33.0,1627904.310,28,7.04,15,1,3,1.56,0.25,0.78,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,Medium

In [3]:
# Separate target first
dependent = dataset["Risk_Level"]
independent = dataset.drop(columns=["Risk_Level"])

In [4]:
corr_matrix=independent.corr()
corr_matrix

,Team_Size,Project_Budget_USD,Estimated_Timeline_Months,Complexity_Score,Stakeholder_Count,Past_Similar_Projects,External_Dependencies_Count,Change_Request_Frequency,Team_Turnover_Rate,Vendor_Reliability_Score,...,onehot__Contract_Type_Hybrid,onehot__Contract_Type_Time & Materials,onehot__Client_Experience_Level_First-time,onehot__Client_Experience_Level_Occasional,onehot__Client_Experience_Level_Regular,onehot__Client_Experience_Level_Strategic,onehot__Team_Colocation_Fully Colocated,onehot__Team_Colocation_Fully Remote,onehot__Team_Colocation_Hybrid,onehot__Team_Colocation_Partially Colocated
Team_Size,1.000000,0.885798,0.864391,0.478861,0.785608,-0.006827,0.334217,0.018489,0.014237,-0.018919,...,-0.027433,0.013431,-0.206223,-0.056001,0.082056,0.180214,-0.029096,0.041999,0.001167,-0.016725
Project_Budget_USD,0.885798,1.000000,0.864842,0.587870,0.886197,-0.002166,0.409297,0.012245,0.023810,-0.022124,...,-0.032565,0.011208,-0.307513,-0.114003,0.130069,0.294793,-0.023697,0.015319,0.000606,0.005824
Estimated_Timeline_Months,0.864391,0.864842,1.000000,0.792578,0.770566,-0.001003,0.553153,0.009925,0.034673,-0.017852,...,-0.034579,0.009205,-0.147251,-0.034156,0.054738,0.126349,-0.022122,0.027830,0.003870,-0.011733
Complexity_Score,0.478861,0.587870,0.792578,1.000000,0.524190,0.009751,0.704350,-0.005723,0.028492,-0.012143,...,-0.040565,0.002917,-0.023610,0.017559,0.006706,-0.003613,-0.005363,-0.022373,0.015837,0.010789
Stakeholder_Count,0.785608,0.886197,0.770566,0.524190,1.000000,-0.009377,0.368666,0.017496,0.008317,-0.020938,...,-0.029288,0.019401,-0.267720,-0.107171,0.107453,0.272096,-0.018989,0.005285,0.007219,0.004595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
onehot__Client_Experience_Level_Strategic,0.180214,0.294793,0.126349,-0.003613,0.272096,-0.003443,-0.015343,0.000262,0.008871,-0.012893,...,0.017030,-0.000458,-0.262210,-0.334075,-0.319075,1.000000,0.003424,0.000624,-0.016857,0.014060
onehot__Team_Colocation_Fully Colocated,-0.029096,-0.023697,-0.022122,-0.005363,-0.018989,0.016541,-0.026417,-0.000663,-0.003356,0.012977,...,-0.007767,0.003806,-0.011943,0.022083,-0.014773,0.003424,1.000000,-0.292259,-0.325065,-0.286302
onehot__Team_Colocation_Fully Remote,0.041999,0.015319,0.027830,-0.022373,0.005285,-0.017192,-0.007281,-0.005035,-0.020005,-0.013115,...,0.033294,-0.001559,0.006100,0.011134,-0.017428,0.000624,-0.292259,1.000000,-0.381204,-0.335747
onehot__Team_Colocation_Hybrid,0.001167,0.000606,0.003870,0.015837,0.007219,-0.012359,0.013201,0.032891,0.020672,-0.003778,...,-0.020116,-0.000527,-0.004572,0.004307,0.014866,-0.016857,-0.325065,-0.381204,1.000000,-0.373434
onehot__Team_Colocation_Partially Colocated,-0.016725,0.005824,-0.011733,0.010789,0.004595,0.015147,0.017831,-0.029149,0.001415,0.005237,...,-0.005130,-0.001391,0.009742,-0.036261,0.015536,0.014060,-0.286302,-0.335747,-0.373434,1.000000

In [5]:
from sklearn.feature_selection import VarianceThreshold
var_selector = VarianceThreshold(threshold=0.01)
X_var = var_selector.fit_transform(independent)

X_var_columns = independent.columns[var_selector.get_support()]

In [6]:
from sklearn.feature_selection import SelectKBest, f_classif

dependent = dependent.ravel()

selector = SelectKBest(score_func=f_classif, k=15)
X_anova = selector.fit_transform(X_var, dependent)

selected_features = X_var_columns[selector.get_support()]
X_selected = independent[selected_features]
X_selected

C:\Users\PRIYANKA MANI\AppData\Local\Temp\ipykernel_23268\421631946.py:3: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  dependent = dependent.ravel()

,Team_Size,Project_Budget_USD,Estimated_Timeline_Months,Complexity_Score,External_Dependencies_Count,Team_Turnover_Rate,Current_Phase_Duration_Months,ord__Technology_Familiarity,ord__Stakeholder_Engagement_Level,ord__Key_Stakeholder_Availability,ord__Industry_Volatility,ord__Change_Control_Maturity,onehot__Project_Type_R&D,onehot__Org_Process_Maturity_Ad-hoc,onehot__Org_Process_Maturity_Optimizing
0,32.0,1526276.550,32,9.70,3,0.16,5,0.0,3.0,2.0,0.0,1.0,0.0,0.0,0.0
1,2.0,390790.150,9,2.72,2,0.42,3,1.0,0.0,0.0,3.0,0.0,0.0,0.0,1.0
2,2.0,246674.760,6,2.04,0,0.55,1,1.0,0.0,3.0,3.0,2.0,0.0,1.0,0.0
3,12.0,1427830.630,17,7.54,5,0.33,6,1.0,3.0,1.0,0.0,2.0,0.0,0.0,0.0
4,24.0,1696746.640,24,6.68,2,0.36,6,0.0,2.0,3.0,2.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,9.0,731548.970,14,5.40,3,0.25,1,1.0,0.0,3.0,2.0,2.0,0.0,1.0,0.0
3996,9.0,492981.400,9,2.69,3,0.06,1,1.0,4.0,2.0,3.0,2.0,0.0,0.0,0.0
3997,12.0,1097040.650,24,8.82,4,0.23,4,2.0,0.0,3.0,2.0,2.0,0.0,1.0,0.0
3998,26.0,2650876.115,28,10.00,6,0.30,10,2.0,3.0,3.0,1.0,1.0,1.0,0.0,0.0
3999,33.0,1627904.310,28,7.04,3,0.25,1,0.0,0.0,3.0,1.0,2.0,0.0,0.0,0.0

In [7]:
X_var_columns

Index(['Team_Size', 'Project_Budget_USD', 'Estimated_Timeline_Months',
       'Complexity_Score', 'Stakeholder_Count', 'Past_Similar_Projects',
       'External_Dependencies_Count', 'Change_Request_Frequency',
       'Team_Turnover_Rate', 'Vendor_Reliability_Score',
       'Historical_Risk_Incidents', 'Communication_Frequency',
       'Geographical_Distribution', 'Budget_Utilization_Rate',
       'Market_Volatility', 'Integration_Complexity', 'Resource_Availability',
       'Organizational_Change_Frequency', 'Cross_Functional_Dependencies',
       'Previous_Delivery_Success_Rate', 'Technical_Debt_Level',
       'Project_Start_Month', 'Current_Phase_Duration_Months',
       'ord__Team_Experience_Level', 'ord__Requirement_Stability',
       'ord__Regulatory_Compliance_Level', 'ord__Technology_Familiarity',
       'ord__Stakeholder_Engagement_Level', 'ord__Executive_Sponsorship',
       'ord__Priority_Level', 'ord__Project_Manager_Experience',
       'ord__Data_Security_Requirements', 'ord__Key_Stakeholder_Availability',
       'ord__Tech_Environment_Stability', 'ord__Resource_Contention_Level',
       'ord__Industry_Volatility', 'ord__Change_Control_Maturity',
       'ord__Risk_Management_Maturity', 'ord__Documentation_Quality',
       'onehot__Project_Type_Construction', 'onehot__Project_Type_Healthcare',
       'onehot__Project_Type_IT', 'onehot__Project_Type_Manufacturing',
       'onehot__Project_Type_Marketing', 'onehot__Project_Type_R&D',
       'onehot__Methodology_Used_Agile', 'onehot__Methodology_Used_Hybrid',
       'onehot__Methodology_Used_Kanban', 'onehot__Methodology_Used_Scrum',
       'onehot__Methodology_Used_Waterfall', 'onehot__Project_Phase_Closure',
       'onehot__Project_Phase_Execution', 'onehot__Project_Phase_Initiation',
       'onehot__Project_Phase_Monitoring', 'onehot__Project_Phase_Planning',
       'onehot__Funding_Source_External', 'onehot__Funding_Source_Government',
       'onehot__Funding_Source_Internal', 'onehot__Funding_Source_Mixed',
       'onehot__Org_Process_Maturity_Ad-hoc',
       'onehot__Org_Process_Maturity_Defined',
       'onehot__Org_Process_Maturity_Managed',
       'onehot__Org_Process_Maturity_Optimizing',
       'onehot__Contract_Type_Cost-Plus', 'onehot__Contract_Type_Fixed-Price',
       'onehot__Contract_Type_Hybrid',
       'onehot__Contract_Type_Time & Materials',
       'onehot__Client_Experience_Level_First-time',
       'onehot__Client_Experience_Level_Occasional',
       'onehot__Client_Experience_Level_Regular',
       'onehot__Client_Experience_Level_Strategic',
       'onehot__Team_Colocation_Fully Colocated',
       'onehot__Team_Colocation_Fully Remote',
       'onehot__Team_Colocation_Hybrid',
       'onehot__Team_Colocation_Partially Colocated'],
      dtype='object')

In [8]:
X_var

array([[3.20000000e+01, 1.52627655e+06, 3.20000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.00000000e+00, 3.90790150e+05, 9.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.00000000e+00, 2.46674760e+05, 6.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       ...,
       [1.20000000e+01, 1.09704065e+06, 2.40000000e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.60000000e+01, 2.65087612e+06, 2.80000000e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.30000000e+01, 1.62790431e+06, 2.80000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [9]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_selected, dependent, test_size = 1/3, random_state =42)
X_train, X_test, Y_train, Y_test

(      Team_Size  Project_Budget_USD  Estimated_Timeline_Months  \
 1251       35.0          2360835.01                         25
 365        18.0          1814824.23                         23
 1366       22.0           772811.99                         21
 276        18.0          1495394.30                         23
 2639        6.0           613149.17                          8
 ...         ...                 ...                        ...
 1130        8.0           411443.47                          8
 1294       10.0           545103.53                         14
 860        14.0          1115158.11                         17
 3507       28.0          1772601.08                         17
 3174        9.0           588795.51                         11

       Complexity_Score  External_Dependencies_Count  Team_Turnover_Rate  \
 1251              5.84                            4                0.15
 365               8.56                            4                0.27
 1366              6.14                            5                0.13
 276               9.51                            3                0.28
 2639              3.34                            0                0.26
 ...                ...                          ...                 ...
 1130              2.49                            3                0.17
 1294              4.90                            4                0.16
 860               7.40                            4                0.10
 3507              3.42                            2                0.54
 3174              3.73                            3                0.12

       Current_Phase_Duration_Months  ord__Technology_Familiarity  \
 1251                              3                          2.0
 365                              10                          2.0
 1366                              4                          2.0
 276                               6                          2.0
 2639                              1                          1.0
 ...                             ...                          ...
 1130                              1                          2.0
 1294                              1                          2.0
 860                               6                          2.0
 3507                              6                          2.0
 3174                              4                          0.0

       ord__Stakeholder_Engagement_Level  ord__Key_Stakeholder_Availability  \
 1251                                4.0                                2.0
 365                                 4.0                                3.0
 1366                                3.0                                2.0
 276                                 2.0                                3.0
 2639                                0.0                                3.0
 ...                                 ...                                ...
 1130                                1.0                                1.0
 1294                                2.0                                0.0
 860                                 3.0                                3.0
 3507                                2.0                                4.0
 3174                                4.0                                2.0

       ord__Industry_Volatility  ord__Change_Control_Maturity  \
 1251                       1.0                           1.0
 365                        1.0                           1.0
 1366                       0.0                           2.0
 276                        0.0                           1.0
 2639                       3.0                           1.0
 ...                        ...                           ...
 1130                       3.0                           2.0
 1294                       0.0                           2.0
 860                        3.0                           2.0
 3507                       3.0                           2.0
 3174                       3.0                           1.0

       onehot__Project_Type_R&D  onehot__Org_Process_Maturity_Ad-hoc  \
 1251                       0.0                                  1.0
 365                        1.0                                  0.0
 1366                       0.0                                  0.0
 276                        0.0                                  1.0
 2639                       0.0                                  0.0
 ...                        ...                                  ...
 1130                       0.0                                  0.0
 1294                       0.0                                  0.0
 860                        1.0                                  0.0
 3507                       0.0                                  0.0
 3174                       0.0                                  0.0

       onehot__Org_Process_Maturity_Optimizing
 1251                                      0.0
 365                                       1.0
 1366                                      0.0
 276                                       0.0
 2639                                      0.0
 ...                                       ...
 1130                                      0.0
 1294                                      0.0
 860                                       1.0
 3507                                      1.0
 3174                                      0.0

 [2666 rows x 15 columns],
       Team_Size  Project_Budget_USD  Estimated_Timeline_Months  \
 555         5.0           740575.90                          9
 3491        3.0           438240.88                          9
 527         3.0           366345.48                          4
 3925       23.0          1813318.22                         22
 2989       17.0          1486216.22                         27
 ...         ...                 ...                        ...
 3138        2.0           422773.78                          7
 498        11.0          1097776.73                         18
 1234       12.0          1150822.95                         17
 1512       10.0           756800.17                         13
 435        11.0           899068.37                         21

       Complexity_Score  External_Dependencies_Count  Team_Turnover_Rate  \
 555               3.50                            1                0.37
 3491              3.88                            3                0.26
 527               2.36                            0                0.22
 3925              5.43                            4                0.32
 2989              9.17                            5                0.22
 ...                ...                          ...                 ...
 3138              3.91                            0                0.52
 498               8.66                            6                0.54
 1234              6.72                            4                0.66
 1512              5.56                            4                0.05
 435               9.24                            6                0.50

       Current_Phase_Duration_Months  ord__Technology_Familiarity  \
 555                               1                          1.0
 3491                              3                          0.0
 527                               1                          2.0
 3925                              4                          1.0
 2989                             11                          0.0
 ...                             ...                          ...
 3138                              2                          2.0
 498                               5                          1.0
 1234                              6                          1.0
 1512                              5                          0.0
 435                               2                          1.0

       ord__Stakeholder_Engagement_Level  ord__Key_Stakeholder_Availability  \
 555                                 1.0                                3.0
 3491                                2.0                                1.0
 527                                 4.0                                2.0
 3925                                0.0                                1.0
 2989                                4.0                                1.0
 ...                                 ...                                ...
 3138                                3.0                                2.0
 498                                 4.0                                4.0
 1234                                0.0                                1.0
 1512                                4.0                                2.0
 435                                 3.0                                2.0

       ord__Industry_Volatility  ord__Change_Control_Maturity  \
 555                        3.0                           2.0
 3491                       3.0                           2.0
 527                        2.0                           2.0
 3925                       3.0                           1.0
 2989                       1.0                           0.0
 ...                        ...                           ...
 3138                       2.0                           1.0
 498                        1.0                           1.0
 1234                       2.0                           2.0
 1512                       2.0                           2.0
 435                        1.0                           0.0

       onehot__Project_Type_R&D  onehot__Org_Process_Maturity_Ad-hoc  \
 555                        0.0                                  0.0
 3491                       0.0                                  0.0
 527                        0.0                                  0.0
 3925                       0.0                                  1.0
 2989                       0.0                                  0.0
 ...                        ...                                  ...
 3138                       0.0                                  0.0
 498                        0.0                                  0.0
 1234                       0.0                                  0.0
 1512                       0.0                                  0.0
 435                        0.0                                  0.0

       onehot__Org_Process_Maturity_Optimizing
 555                                       0.0
 3491                                      0.0
 527                                       0.0
 3925                                      0.0
 2989                                      1.0
 ...                                       ...
 3138                                      0.0
 498                                       0.0
 1234                                      1.0
 1512                                      0.0
 435                                       0.0

 [1334 rows x 15 columns],
 array(['High', 'Critical', 'High', ..., 'Low', 'High', 'Low'],
       dtype=object),
 array(['Medium', 'Medium', 'Critical', ..., 'High', 'Medium', 'High'],
       dtype=object))

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(solver='lbfgs')
classifier.fit(X_train,Y_train)
classifier

LogisticRegression()

In [12]:
y_pred=classifier.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)

# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, y_pred)

In [13]:
from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,y_pred,average='weighted')
print("The f1_macro value for best parameter {}:".format(classifier),f1_macro)

The f1_macro value for best parameter LogisticRegression(): 0.5107024807374309

In [14]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[137  85   5  53]
 [ 46 122  11 137]
 [  2  12 129 126]
 [ 12  89  75 293]]

In [15]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

    Critical       0.70      0.49      0.57       280
        High       0.40      0.39      0.39       316
         Low       0.59      0.48      0.53       269
      Medium       0.48      0.62      0.54       469

    accuracy                           0.51      1334
   macro avg       0.54      0.49      0.51      1334
weighted avg       0.53      0.51      0.51      1334

In [16]:
from sklearn.metrics import roc_auc_score

y_prob = classifier.predict_proba(X_test)

roc_auc = roc_auc_score(Y_test,y_prob,   multi_class="ovo",   # or "ovo"   
                        average="weighted")

print("ROC AUC:", roc_auc)

ROC AUC: 0.7736234321659557

In [17]:
classifier.coef_[0]

array([ 0.51864097, -0.53664792, -0.11419459,  0.69032019,  0.15383217,
        0.41141669,  0.01153684,  0.67918092,  0.34322377,  0.43362849,
       -0.31045169,  0.36366739, -0.02118234,  0.62897525, -0.55245602])

In [18]:
X_selected.columns

Index(['Team_Size', 'Project_Budget_USD', 'Estimated_Timeline_Months',
       'Complexity_Score', 'External_Dependencies_Count', 'Team_Turnover_Rate',
       'Current_Phase_Duration_Months', 'ord__Technology_Familiarity',
       'ord__Stakeholder_Engagement_Level',
       'ord__Key_Stakeholder_Availability', 'ord__Industry_Volatility',
       'ord__Change_Control_Maturity', 'onehot__Project_Type_R&D',
       'onehot__Org_Process_Maturity_Ad-hoc',
       'onehot__Org_Process_Maturity_Optimizing'],
      dtype='object')

In [19]:
X_selected.dtypes

Team_Size                                  float64
Project_Budget_USD                         float64
Estimated_Timeline_Months                    int64
Complexity_Score                           float64
External_Dependencies_Count                  int64
Team_Turnover_Rate                         float64
Current_Phase_Duration_Months                int64
ord__Technology_Familiarity                float64
ord__Stakeholder_Engagement_Level          float64
ord__Key_Stakeholder_Availability          float64
ord__Industry_Volatility                   float64
ord__Change_Control_Maturity               float64
onehot__Project_Type_R&D                   float64
onehot__Org_Process_Maturity_Ad-hoc        float64
onehot__Org_Process_Maturity_Optimizing    float64
dtype: object